server:
  port: 8080
  servlet:
    cookie:
    context-path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .js

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todoapp?serverTimezone=Asia/Seoul
    username: chan
    password: chan1234

  jpa:
    generate-ddl: true
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate.format_sql: true



    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true




